[platformio]
default_envs = arduino_nano_esp32

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17
build_flags = -std=gnu++20
lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^1.2.4
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    bblanchon/ArduinoJson @ ^7.0.0

[env:native]
platform = native
test_framework = unity
build_flags = -std=c++20 -DNATIVE_TEST
