# tools/build_web.py  (run before each build)

import subprocess
from pathlib import Path

Import("env")  # noqa: F821  – SCons injects this

# ---------------------------------------------------------------------------
# Helper – write a file only when content actually changed (avoids rebuilds)
# ---------------------------------------------------------------------------
def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
build_dir   = Path(env.subst("$BUILD_DIR"))     # noqa: F821
project_dir = Path(env.subst("$PROJECT_DIR"))   # noqa: F821
gen_dir     = build_dir / "generated"
gen_dir.mkdir(parents=True, exist_ok=True)

# Inject generated/ into the compiler include path
env.Append(CPPPATH=[str(gen_dir)])           # noqa: F821

# ---------------------------------------------------------------------------
# TypeScript build
# ---------------------------------------------------------------------------
web_dir = project_dir / "web"

if not (web_dir / "node_modules").exists():
    print("[codegen] npm install ...")
    result = subprocess.run(["npm", "install"], cwd=web_dir, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"[codegen] npm install failed:\n{result.stderr}")
        exit(1)
    print("[codegen] npm install done")

print("[codegen] npm run build ...")
result = subprocess.run(["npm", "run", "build"], cwd=web_dir, capture_output=True, text=True)
if result.returncode != 0:
    print(f"[codegen] npm run build failed:\n{result.stderr}")
    exit(1)
print("[codegen] TypeScript build done")

# ---------------------------------------------------------------------------
# Map:  output_header -> (C variable name, source file relative to project_dir)
# ---------------------------------------------------------------------------
files = {
    "WebUI.h": ("HTML", "web/index.html"),
    "WebCSS.h": ("CSS", "web/styles.css"),
    "WebJS.h":  ("JS",  "web/script.js"),
}

# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------
for header, (varname, srcfile) in files.items():
    src_path = project_dir / srcfile
 
    if not src_path.exists():
        print(f"[codegen] ERROR: source not found: {src_path}")
        exit(1)
 
    content = src_path.read_text(encoding="utf-8")
 
    data = (
        '#pragma once\n'
        '\n'
        '#include <Arduino.h>\n'
        '\n'
        f'// Auto-generated by tools/build_web.py — do not edit manually.\n'
        f'const char {varname}[] PROGMEM = R"rawhtml({content})rawhtml";\n'
    )
 
    changed = write_if_changed(gen_dir / header, data)
    print(f"[codegen] {header} {'updated' if changed else 'unchanged'}")