#include "WebUI.h"

// Auto-generated by tools/build_web.py — do not edit manually.
// Run `python tools/build_web.py` to regenerate from web/index.html.

const char WEB_UI_HTML[] PROGMEM = R"rawhtml(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Carb Balancer</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: sans-serif; background: #1a1a1a; color: #eee; min-height: 100vh; }

header {
  display: flex; align-items: center; gap: 0.75rem;
  padding: 0.9rem 1.5rem;
  background: #222; border-bottom: 1px solid #333;
}
h1 { font-size: 1.05rem; font-weight: 600; flex: 1; }
#rpm { font-size: 0.85rem; color: #999; min-width: 6rem; text-align: right; }
#dot { font-size: 1.1rem; color: #444; transition: color 0.3s; }
#dot.ok { color: #4caf50; }
#hbtns { display: flex; gap: 0.5rem; align-items: center; }
@media (max-width: 520px) {
  header { flex-wrap: wrap; padding: 0.75rem 1rem; }
  #hbtns { width: 100%; justify-content: flex-end; }
}

.hbtn {
  padding: 0.35rem 1.1rem; border: none; border-radius: 4px;
  cursor: pointer; font-size: 0.85rem; font-weight: 600;
  transition: background 0.2s;
}
.hbtn:disabled { background: #555 !important; cursor: default; }
#btn       { background: #4caf50; color: #fff; }
#btn.running { background: #e53935; }
#btn_usb   { background: #1565c0; color: #fff; }
#btn_usb.running { background: #e53935; }
#sel_view {
  background: #333; color: #eee; border: 1px solid #555; border-radius: 4px;
  padding: 0.35rem 0.5rem; font-size: 0.85rem; font-weight: 600; cursor: pointer;
}
#btn_settings { background: #333; color: #eee; border: 1px solid #555; }
#btn_settings.active { border-color: #4caf50; color: #4caf50; }

/* Status bar */
#status {
  text-align: center;
  padding: 0.55rem 1.5rem;
  font-size: 0.95rem; font-weight: 600; letter-spacing: 0.06em;
  color: #444;
  border-bottom: 1px solid #2a2a2a;
}
#status.sync   { color: #4caf50; }
#status.almost { color: #ffc107; }
#status.desync { color: #ef5350; }

/* Grid */
main {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem; padding: 1.5rem;
}
@media (max-width: 520px) {
  main { grid-template-columns: 1fr; padding: 1rem; }
}

/* Waveform plot */
#wave-wrap { display: flex; flex-direction: column; padding: 1rem; gap: 0.5rem; height: 400px; overflow: hidden; }
#wave-ctrl { flex-shrink: 0; display: flex; flex-direction: column; gap: 0.35rem; }
#wave-ch-btns { display: flex; gap: 0.4rem; flex-wrap: wrap; }
#wave-ctrl button {
  padding: 0.2rem 0.7rem; border-radius: 4px; border: 2px solid; font-size: 0.8rem;
  font-weight: 600; cursor: pointer; background: transparent; transition: opacity 0.2s;
}
#wave-ctrl button.off { opacity: 0.3; }
.wslider { display: flex; align-items: center; gap: 0.5rem; }
.wslider > span:first-child { font-size: 0.75rem; color: #777; min-width: 2.8rem; }
.wslider > span:last-child  { font-size: 0.75rem; color: #777; min-width: 2.5rem; text-align: right; }
.wslider input[type=range]  { flex: 1; accent-color: #4caf50; cursor: pointer; }
#wave-canvas { display: block; width: 100%; flex: 1; min-height: 0; border-radius: 8px; border: 1px solid #333; }

/* Card view */
.cyl {
  background: #252525; border: 1px solid #333; border-radius: 8px;
  padding: 1rem; text-align: center;
  height: 200px; box-sizing: border-box; overflow: hidden;
}
.cyl.ref { border-color: #4caf50; }
.cyl-label { font-size: 0.7rem; color: #777; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.6rem; }
.cyl-kpa   { font-size: 1.9rem; font-weight: 700; font-variant-numeric: tabular-nums; }
.cyl-unit  { font-size: 0.7rem; color: #777; margin-top: 0.1rem; }
.cyl-delta { font-size: 0.8rem; margin-top: 0.5rem; font-variant-numeric: tabular-nums; }

/* Gauge view */
.gauge-card {
  background: #252525; border: 1px solid #333; border-radius: 8px;
  padding: 0.75rem; text-align: center;
  height: 300px; box-sizing: border-box; overflow: hidden;
}
.gauge-card.ref { border-color: #4caf50; }
.gauge-label { font-size: 0.7rem; color: #777; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.3rem; }
.gauge-svg svg { max-height: 230px; }
.gauge-delta { font-size: 0.8rem; margin-top: 0.2rem; font-variant-numeric: tabular-nums; }

/* Shared delta colours */
.pos  { color: #ef5350; }
.neg  { color: #42a5f5; }
.zero { color: #666; }

/* Settings panel */
#settings-panel { display: none; padding: 1.5rem; max-width: 480px; margin: 0 auto; }
#settings-panel h2 { font-size: 1rem; font-weight: 600; margin-bottom: 1rem; color: #ccc; }
.sgroup { background: #252525; border: 1px solid #333; border-radius: 8px; padding: 0.75rem 1rem; margin-bottom: 0.75rem; }
.srow { display: grid; grid-template-columns: 1fr 1fr; gap: 0.5rem; align-items: center; padding: 0.3rem 0; }
.srow label { font-size: 0.8rem; color: #999; }
.srow input { background: #1a1a1a; border: 1px solid #444; border-radius: 4px; color: #eee; padding: 0.35rem 0.6rem; font-size: 0.85rem; width: 100%; }
.srow input:focus { outline: none; border-color: #4caf50; }
#s_footer { display: flex; align-items: center; justify-content: flex-end; gap: 1rem; margin-top: 0.5rem; }
#s_msg { font-size: 0.8rem; }
#s_msg.ok  { color: #4caf50; }
#s_msg.err { color: #ef5350; }
</style>
</head>
<body>
<header>
  <h1>Carb Balancer</h1>
  <span id="rpm">-- RPM</span>
  <span id="dot" title="WebSocket status">●</span>
  <div id="hbtns">
    <select id="sel_view" onchange="setView(this.value)">
      <option value="card">Card</option>
      <option value="gauge" selected>Gauge</option>
    </select>
    <button id="btn"          class="hbtn" onclick="toggleRun()"      disabled>Start</button>
    <button id="btn_usb"      class="hbtn" onclick="togglePlot()"     disabled>Start Plot</button>
    <button id="btn_settings" class="hbtn" onclick="toggleSettings()">⚙</button>
  </div>
</header>
<div id="status">--</div>
<main id="grid"></main>
<div id="wave-wrap">
  <div id="wave-ctrl">
    <div id="wave-ch-btns"></div>
    <div class="wslider">
      <span>Timebase</span>
      <input type="range" id="wave-zoom" min="20" max="1200" oninput="onWaveZoom(this.value)">
      <span id="wave-zoom-val">400</span>
    </div>
    <div class="wslider">
      <span>Span</span>
      <input type="range" id="wave-span" min="100" max="1000" value="200" oninput="onWaveSpan(this.value)">
      <span id="wave-span-val">200</span>
    </div>
    <div class="wslider" id="wave-scroll-row" style="display:none">
      <span>Scroll</span>
      <input type="range" id="wave-scroll" min="0" max="0" value="0" oninput="onWaveScroll(this.value)">
      <span id="wave-scroll-val"></span>
    </div>
  </div>
  <canvas id="wave-canvas"></canvas>
</div>

<div id="settings-panel">
  <h2>Settings</h2>
  <div class="sgroup">
    <div class="srow"><label>Cylinders</label>
      <input type="number" id="s_cyl" min="1" max="4" step="1"></div>
    <div class="srow"><label>Reference cylinder</label>
      <input type="number" id="s_ref" min="1" max="4" step="1"></div>
    <div class="srow"><label>EMA damping (0-16)</label>
      <input type="number" id="s_damp" min="0" max="16" step="1"></div>
    <div class="srow"><label>RPM damping (0-16)</label>
      <input type="number" id="s_rdamp" min="0" max="16" step="1"></div>
    <div class="srow"><label>Update interval (ms)</label>
      <input type="number" id="s_interval" min="50" max="5000" step="10"></div>
  </div>
  <div class="sgroup">
    <div class="srow"><label>WiFi SSID</label>
      <input type="text" id="s_ssid" maxlength="32" autocomplete="off"></div>
    <div class="srow"><label>WiFi password</label>
      <input type="password" id="s_pw" maxlength="63" autocomplete="new-password"></div>
  </div>
  <div id="s_footer">
    <span id="s_msg"></span>
    <button class="hbtn" id="s_save" style="background:#4caf50;color:#fff" onclick="saveSettings()">Save</button>
  </div>
</div>

<script>
(function () {
  var ws, running = false, ref = 0, connected = false, plot = false, plotFrozen = false;
  var viewMode = 'gauge';
  var settingsOpen = false, settingsSaved = false;
  var lastData = null;
  var cylCount = 4;
  var visibleChs = [true, true, true, true];
  var viewPts    = window.matchMedia('(max-width: 520px)').matches ? 100 : 400;
  var viewOffset = 0;  // 0 = newest, positive = steps back from the right
  var waveSpan   = 200;

  // Wave data: always accumulated, per-channel array of {t, v} (v = kPa × 10 integer)
  var WAVE_MAX = 1200;  // ~5.5 s at 215 Hz
  var waveChs = [[], [], [], []];
  var waveRaf = null;
  var CH_COLORS = ['#4caf50', '#42a5f5', '#ffc107', '#ef5350'];

  function appendWave(msg) {
    var t0 = msg.t0 || 0, dt = msg.dt || 5, chs = msg.chs || [];
    for (var c = 0; c < chs.length && c < 4; c++) {
      for (var i = 0; i < chs[c].length; i++)
        waveChs[c].push({t: t0 + i * dt, v: chs[c][i] / 10});
      if (waveChs[c].length > WAVE_MAX)
        waveChs[c] = waveChs[c].slice(waveChs[c].length - WAVE_MAX);
    }
    updateScrollSlider();
  }

  function maxDataLen() {
    var n = 0;
    for (var c = 0; c < cylCount; c++) n = Math.max(n, waveChs[c].length);
    return n;
  }

  function updateScrollSlider() {
    var maxOff = Math.max(0, maxDataLen() - viewPts);
    var row    = document.getElementById('wave-scroll-row');
    var sl     = document.getElementById('wave-scroll');
    if (maxOff > 0) {
      sl.max = maxOff;
      // keep viewOffset clamped; if at zero (live view) stay at max (right edge)
      viewOffset = Math.min(viewOffset, maxOff);
      sl.value = maxOff - viewOffset;   // right = newest (offset 0)
      row.style.display = '';
    } else {
      viewOffset = 0;
      row.style.display = 'none';
    }
  }

  window.onWaveZoom = function(val) {
    viewPts = parseInt(val);
    document.getElementById('wave-zoom-val').textContent = val;
    updateScrollSlider();
  };

  window.onWaveSpan = function(val) {
    waveSpan = parseInt(val);
    document.getElementById('wave-span-val').textContent = val;
  };

  window.onWaveScroll = function(val) {
    var sl = document.getElementById('wave-scroll');
    viewOffset = parseInt(sl.max) - parseInt(val);  // right = 0 = newest
  };

  function niceStep(rough) {
    var p = Math.pow(10, Math.floor(Math.log10(rough || 1)));
    var f = rough / p;
    return f < 1.5 ? p : f < 3.5 ? 2*p : f < 7.5 ? 5*p : 10*p;
  }

  function drawWave() {
    var canvas = document.getElementById('wave-canvas');
    var w = canvas.clientWidth, h = canvas.clientHeight;
    if (canvas.width !== w) canvas.width = w;
    if (canvas.height !== h) canvas.height = h;
    var ctx = canvas.getContext('2d');
    ctx.fillStyle = '#1a1a1a'; ctx.fillRect(0, 0, w, h);

    var mobile = window.matchMedia('(max-width: 520px)').matches;
    var ml = mobile ? 34 : 46, mr = 8, mt = 14, mb = mobile ? 16 : 22;
    var pw = w - ml - mr, ph = h - mt - mb;

    // Slice viewPts samples at viewOffset from the end, per channel
    var showLines = plot || plotFrozen;
    var slices = [];
    var yMin = Infinity, yMax = -Infinity;
    if (showLines) {
      for (var c = 0; c < cylCount; c++) {
        var d = waveChs[c];
        var end   = d.length - viewOffset;
        var start = Math.max(0, end - viewPts);
        var sl = d.slice(start, end);
        slices.push(sl);
        if (!visibleChs[c]) continue;
        for (var i = 0; i < sl.length; i++) {
          yMin = Math.min(yMin, sl[i].v); yMax = Math.max(yMax, sl[i].v);
        }
      }
    }
    var center = isFinite(yMin) ? (yMin + yMax) / 2 : 200;
    yMin = center - waveSpan / 2;
    yMax = center + waveSpan / 2;

    // right-aligned index mapping: newest sample always at the right edge
    function tx(off) { return ml + off / viewPts * pw; }
    function ty(v)   { return mt + (1 - (v - yMin) / (yMax - yMin)) * ph; }

    // Y grid + labels
    var step = niceStep((yMax - yMin) / 4);
    ctx.lineWidth = 1;
    for (var y = Math.ceil(yMin / step) * step; y <= yMax; y += step) {
      var yy = ty(y);
      ctx.strokeStyle = '#2a2a2a'; ctx.beginPath(); ctx.moveTo(ml, yy); ctx.lineTo(ml + pw, yy); ctx.stroke();
      ctx.fillStyle = '#555'; ctx.font = (mobile ? '9' : '10') + 'px sans-serif'; ctx.textAlign = 'right';
      ctx.fillText(y.toFixed(0), ml - 4, yy + 3);
    }
    ctx.fillStyle = '#444'; ctx.font = '9px sans-serif'; ctx.textAlign = 'left';
    ctx.fillText('kPa', 2, mt + 9);

    // Legend — always shown
    for (var c = 0; c < cylCount; c++) {
      var lx = ml + 6 + c * 58;
      ctx.fillStyle = CH_COLORS[c]; ctx.fillRect(lx, mt + 2, 12, 2);
      ctx.fillStyle = '#999'; ctx.font = '10px sans-serif'; ctx.textAlign = 'left';
      ctx.fillText('Cyl ' + (c + 1), lx + 15, mt + 6);
    }

    // Channel lines — when plot is active or frozen
    if (showLines && slices.length > 0) {
      for (var c = 0; c < cylCount; c++) {
        var sl = slices[c]; if (!visibleChs[c] || sl.length < 2) continue;
        var off = viewPts - sl.length;
        ctx.strokeStyle = CH_COLORS[c]; ctx.lineWidth = 1.5; ctx.beginPath();
        for (var i = 0; i < sl.length; i++) {
          var px = tx(off + i), py = ty(sl[i].v);
          if (i === 0) ctx.moveTo(px, py); else ctx.lineTo(px, py);
        }
        ctx.stroke();
      }
      if (plotFrozen) {
        ctx.fillStyle = '#666'; ctx.font = '11px sans-serif'; ctx.textAlign = 'right';
        ctx.fillText('Frozen', ml + pw - 4, mt + 12);
      }
    } else if (!showLines) {
      ctx.fillStyle = '#444'; ctx.font = '13px sans-serif'; ctx.textAlign = 'center';
      ctx.fillText('Press Start Plot to begin', w / 2, h / 2);
    }
  }

  function startWaveRender() {
    if (waveRaf) return;
    function tick() { drawWave(); waveRaf = requestAnimationFrame(tick); }
    waveRaf = requestAnimationFrame(tick);
  }

  function showView() {
    var n = document.getElementById('grid').children.length;
    if (n > 0) { buildGrid(n); if (lastData) update(lastData); }
  }

  // Gauge geometry — viewBox "0 0 260 150", semicircle, 0-140 kPa left→right
  var G = { min: 0, max: 140, cx: 130, cy: 140, r: 90, sw: 14 };

  // -------------------------------------------------------------------------
  // WebSocket
  // -------------------------------------------------------------------------

  function connect() {
    ws = new WebSocket('ws://' + location.host + '/ws');
    ws.onopen = function () {
      connected = true;
      document.getElementById('dot').className = 'ok';
      document.getElementById('btn').disabled = false;
      document.getElementById('btn_usb').disabled = false;
      ws.send(JSON.stringify({ cmd: 'get_settings' }));
    };
    ws.onclose = function () {
      connected = false;
      document.getElementById('dot').className = '';
      document.getElementById('btn').disabled = true;
      document.getElementById('btn_usb').disabled = true;
      setTimeout(connect, 2000);
    };
    ws.onmessage = function (e) {
      var d;
      try { d = JSON.parse(e.data); } catch (_) { return; }
      if (d.type === 'wave') { appendWave(d); return; }
      if (d.type === 'settings') {
        populateSettings(d);
        if (!running) {
          var n = d.cylinder_count, r = d.reference_cylinder;
          update({ rpm: 0, ref: r,
            cylinders: Array.from({length: n}, function () { return { kpa: 0, delta_kpa: 0 }; })
          });
        }
        return;
      }
      if (d.type === 'settings_saved') { showSettingsMsg('Saved', 'ok'); return; }
      if (d.type) return;  // ignore cal_progress / cal_complete
      update(d);
    };
  }

  // -------------------------------------------------------------------------
  // Sync status
  // -------------------------------------------------------------------------

  function updateStatus(cyls) {
    var el = document.getElementById('status');
    if (!running) { el.textContent = '--'; el.className = ''; return; }
    var maxDelta = 0;
    cyls.forEach(function (c, i) {
      if (i !== ref) maxDelta = Math.max(maxDelta, Math.abs(c.delta_kpa));
    });
    if (maxDelta < 5) {
      el.textContent = 'Synchronized';
      el.className   = 'sync';
    } else if (maxDelta < 10) {
      el.textContent = 'Almost Synchronized';
      el.className   = 'almost';
    } else {
      el.textContent = 'Desynchronized';
      el.className   = 'desync';
    }
  }

  // -------------------------------------------------------------------------
  // Gauge helpers
  // -------------------------------------------------------------------------

  function cylColor(absDelta, isRef) {
    if (isRef || absDelta < 5)  return '#4caf50';
    if (absDelta < 10)          return '#ffc107';
    return '#ef5350';
  }

  function makeSvg(kpa, color) {
    var cx = G.cx, cy = G.cy, r = G.r, sw = G.sw;
    var lx = cx - r, rx = cx + r;  // arc left (0 kPa) and right (140 kPa) endpoints

    // Clamp fraction; avoid degenerate arcs at exact 0° or 180°
    var f  = Math.min(0.9999, Math.max(0.0001, (kpa - G.min) / (G.max - G.min)));
    // angle from positive x-axis: π at kpa=0 (left), 0 at kpa=140 (right)
    var a  = Math.PI * (1 - f);
    var ex = (cx + r * Math.cos(a)).toFixed(1);
    var ey = (cy - r * Math.sin(a)).toFixed(1);  // SVG y-axis points down

    // sweep-flag=1 → clockwise on screen → from left (9 o'clock) goes UP through top → upper semicircle ✓
    var bgArc = 'M ' + lx + ' ' + cy + ' A ' + r + ' ' + r + ' 0 0 1 ' + rx + ' ' + cy;
    var fgArc = 'M ' + lx + ' ' + cy + ' A ' + r + ' ' + r + ' 0 0 1 ' + ex + ' ' + ey;

    var s = '<svg viewBox="0 0 260 150" width="100%" xmlns="http://www.w3.org/2000/svg">';

    // Background (full semicircle) and foreground (filled to current value)
    s += '<path d="' + bgArc + '" stroke="#282828" stroke-width="' + sw + '" fill="none" stroke-linecap="round"/>';
    s += '<path d="' + fgArc + '" stroke="' + color + '" stroke-width="' + sw + '" fill="none" stroke-linecap="round"/>';

    // Scale ticks and labels at every 20 kPa
    var rTi = r + sw / 2 + 3;   // tick inner radius (just outside arc)
    var rTo = rTi + 8;           // tick outer radius
    var rLb = rTo + 12;          // label centre radius
    [0, 20, 40, 60, 80, 100, 120, 140].forEach(function (v) {
      var ta = Math.PI * (1 - v / G.max);
      var ca = Math.cos(ta), sa = Math.sin(ta);
      var x1 = (cx + rTi * ca).toFixed(1), y1 = (cy - rTi * sa).toFixed(1);
      var x2 = (cx + rTo * ca).toFixed(1), y2 = (cy - rTo * sa).toFixed(1);
      var lbx = (cx + rLb * ca).toFixed(1), lby = (cy - rLb * sa + 3.5).toFixed(1);
      s += '<line x1="'+x1+'" y1="'+y1+'" x2="'+x2+'" y2="'+y2+'" stroke="#484848" stroke-width="1.5"/>';
      s += '<text x="'+lbx+'" y="'+lby+'" text-anchor="middle" fill="#555" font-size="9" font-family="sans-serif">'+v+'</text>';
    });

    // Current value in the centre of the gauge
    s += '<text x="' + cx + '" y="' + (cy - 22) + '" text-anchor="middle" fill="#eee" font-size="22" font-weight="700" font-family="sans-serif">' + kpa.toFixed(1) + '</text>';
    s += '<text x="' + cx + '" y="' + (cy - 6)  + '" text-anchor="middle" fill="#555" font-size="9"  font-family="sans-serif">kPa</text>';

    s += '</svg>';
    return s;
  }

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------

  function update(d) {
    lastData = d;
    ref = d.ref || 0;
    document.getElementById('rpm').textContent = d.rpm > 0 ? d.rpm + ' RPM' : '-- RPM';

    var cyls = (d.cylinders || []).slice(0, cylCount);
    updateStatus(cyls);

    var grid = document.getElementById('grid');
    if (grid.children.length !== cylCount) buildGrid(cylCount);

    cyls.forEach(function (c, i) {
      var card     = grid.children[i];
      var isRef    = (i === ref);
      var absDelta = Math.abs(c.delta_kpa);
      var color    = cylColor(absDelta, isRef);
      var dText    = isRef ? 'ref' : (c.delta_kpa >= 0 ? '+' : '') + c.delta_kpa.toFixed(2) + ' kPa';
      var dCls     = isRef ? 'zero' : (absDelta < 0.5 ? 'zero' : c.delta_kpa > 0 ? 'pos' : 'neg');

      if (viewMode === 'gauge') {
        card.className = 'gauge-card' + (isRef ? ' ref' : '');
        card.querySelector('.gauge-svg').innerHTML = makeSvg(c.kpa, color);
        var dt = card.querySelector('.gauge-delta');
        dt.textContent = dText;
        dt.className   = 'gauge-delta ' + dCls;
      } else {
        card.className = 'cyl' + (isRef ? ' ref' : '');
        card.querySelector('.cyl-kpa').textContent = c.kpa.toFixed(1);
        var dt = card.querySelector('.cyl-delta');
        dt.textContent = dText;
        dt.className   = 'cyl-delta ' + dCls;
      }
    });
  }

  function buildWaveControls() {
    document.getElementById('wave-zoom').value = viewPts;
    document.getElementById('wave-zoom-val').textContent = viewPts;
    var ctrl = document.getElementById('wave-ch-btns');
    ctrl.innerHTML = '';
    for (var c = 0; c < cylCount; c++) {
      (function(ch) {
        var btn = document.createElement('button');
        btn.textContent = 'Cyl ' + (ch + 1);
        btn.style.color = CH_COLORS[ch];
        btn.style.borderColor = CH_COLORS[ch];
        btn.className = visibleChs[ch] ? '' : 'off';
        btn.onclick = function() {
          visibleChs[ch] = !visibleChs[ch];
          btn.className = visibleChs[ch] ? '' : 'off';
        };
        ctrl.appendChild(btn);
      }(c));
    }
  }

  function buildGrid(n) {
    var grid = document.getElementById('grid');
    grid.innerHTML = '';
    for (var i = 0; i < n; i++) {
      grid.innerHTML += viewMode === 'gauge'
        ? '<div class="gauge-card">' +
            '<div class="gauge-label">Cyl ' + (i + 1) + '</div>' +
            '<div class="gauge-svg"></div>' +
            '<div class="gauge-delta zero">---</div>' +
          '</div>'
        : '<div class="cyl">' +
            '<div class="cyl-label">Cyl ' + (i + 1) + '</div>' +
            '<div class="cyl-kpa">--.-</div>' +
            '<div class="cyl-unit">kPa</div>' +
            '<div class="cyl-delta zero">---</div>' +
          '</div>';
    }
  }

  // -------------------------------------------------------------------------
  // Settings
  // -------------------------------------------------------------------------

  window.toggleSettings = function () {
    settingsOpen = !settingsOpen;
    document.getElementById('settings-panel').style.display = settingsOpen ? 'block' : 'none';
    document.getElementById('status').style.display         = settingsOpen ? 'none' : '';
    document.getElementById('grid').style.display           = settingsOpen ? 'none' : '';
    document.getElementById('wave-wrap').style.display      = settingsOpen ? 'none' : '';
    if (settingsOpen) {
      settingsSaved = false;
    } else if (settingsSaved) {
      location.reload();
      return;
    }
    var btn = document.getElementById('btn_settings');
    btn.textContent = settingsOpen ? '✕' : '⚙';
    btn.className   = 'hbtn' + (settingsOpen ? ' active' : '');
    if (settingsOpen && connected) {
      if (running) {
        running = false;
        ws.send(JSON.stringify({ cmd: 'stop' }));
        var btnRun = document.getElementById('btn');
        btnRun.textContent = 'Start';
        btnRun.className   = 'hbtn';
      }
      ws.send(JSON.stringify({ cmd: 'get_settings' }));
    }
  };

  function populateSettings(d) {
    document.getElementById('s_cyl').value      = d.cylinder_count;
    document.getElementById('s_ref').value      = d.reference_cylinder + 1;
    document.getElementById('s_damp').value     = d.damping;
    document.getElementById('s_rdamp').value    = d.rpm_damping;
    document.getElementById('s_interval').value = d.update_interval_ms;
    document.getElementById('s_ssid').value     = d.ap_ssid;
    document.getElementById('s_pw').value       = d.ap_password;
    cylCount = d.cylinder_count || cylCount;
    buildWaveControls();
  }

  function showSettingsMsg(text, cls) {
    var el = document.getElementById('s_msg');
    el.textContent = text;
    el.className   = cls;
    setTimeout(function () { el.textContent = ''; el.className = ''; }, 3000);
  }

  window.saveSettings = function () {
    if (!connected) return;
    cylCount = parseInt(document.getElementById('s_cyl').value, 10) || cylCount;
    settingsSaved = true;
    ws.send(JSON.stringify({
      cmd:                  'set_settings',
      cylinder_count:        cylCount,
      reference_cylinder:    parseInt(document.getElementById('s_ref').value,      10) - 1,
      damping:               parseInt(document.getElementById('s_damp').value,     10),
      rpm_damping:           parseInt(document.getElementById('s_rdamp').value,    10),
      update_interval_ms:    parseInt(document.getElementById('s_interval').value, 10),
      ap_ssid:               document.getElementById('s_ssid').value,
      ap_password:           document.getElementById('s_pw').value,
    }));
  };

  // -------------------------------------------------------------------------
  // Controls
  // -------------------------------------------------------------------------

  window.setView = function (mode) {
    viewMode = mode;
    showView();
  };

  window.toggleRun = function () {
    if (!connected) return;
    running = !running;
    ws.send(JSON.stringify({ cmd: running ? 'start' : 'stop' }));
    var btn = document.getElementById('btn');
    btn.textContent = running ? 'Stop' : 'Start';
    btn.className   = 'hbtn' + (running ? ' running' : '');
  };

  window.togglePlot = function () {
    if (!connected || !running) return;
    plot = !plot;
    if (plot) {
      waveChs = [[], [], [], []];
      plotFrozen = false;
      viewOffset = 0;
      updateScrollSlider();
    } else {
      plotFrozen = true;
    }
    ws.send(JSON.stringify({ cmd: 'wave', enabled: plot }));
    var btn = document.getElementById('btn_usb');
    btn.textContent = plot ? 'Stop Plot' : 'Start Plot';
    btn.className   = 'hbtn' + (plot ? ' running' : '');
  };

  buildWaveControls();
  startWaveRender();
  connect();
}());
</script>
</body>
</html>
)rawhtml";
